/*
 * Copyright 2016 Morten Laukvik <morten@laukvik.no>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.laukvik.csv.ui;

import javax.swing.*;
import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author Morten Laukvik <morten@laukvik.no>
 */
public class ExplorerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExplorerPanel
     */
    public ExplorerPanel() {
        initComponents();
        fixTable(columnsTable);
        fixTable(uniqueTable);
        fixTable(resultsTable);
        columnsTable.setTableHeader(null);
        uniqueTable.setTableHeader(null);
        resultsTable.getTableHeader().setReorderingAllowed(true);
        //resultsTable.getTableHeader().setFont(null);

        Font font = new Font( resultsTable.getFont().getFamily(), Font.BOLD, 12 );
        resultsTable.getTableHeader().setFont(font);
        resultsTable.setRowHeight(30);
    }

    public void fixTable(JTable t){
        t.setRowHeight(20);
        t.setCellSelectionEnabled(false);
        t.setColumnSelectionAllowed(false);
        t.setRowSelectionAllowed(true);
        t.setIntercellSpacing(new Dimension(0, 0));
    }

    public JTable getColumnsTable() {
        return columnsTable;
    }

    public void setColumnsTable(JTable columnsTable) {
        this.columnsTable = columnsTable;
    }


    public JTable getResultsTable() {
        return resultsTable;
    }

    public void setResultsTable(JTable resultsTable) {
        this.resultsTable = resultsTable;
    }

    public JTable getUniqueTable() {
        return uniqueTable;
    }

    public void setUniqueTable(JTable uniqueTable) {
        this.uniqueTable = uniqueTable;
    }



    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        uniqueTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        columnsTable = new javax.swing.JTable();
        jSplitPane3 = new javax.swing.JSplitPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        detailsPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rowsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        columnsLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        charsetLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        separatorLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(250);

        jSplitPane2.setBorder(null);
        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane2.setRowHeaderView(null);

        uniqueTable.setAutoCreateRowSorter(true);
        uniqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(uniqueTable);

        jSplitPane2.setBottomComponent(jScrollPane2);

        columnsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(columnsTable);

        jSplitPane2.setLeftComponent(jScrollPane1);

        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane3.setBorder(null);
        jSplitPane3.setDividerLocation(200);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane5.setViewportView(detailsPanel);

        jSplitPane3.setRightComponent(jScrollPane5);

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(resultsTable);

        jSplitPane3.setTopComponent(jScrollPane4);

        jSplitPane1.setRightComponent(jSplitPane3);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Rows:");
        jLabel1.setEnabled(false);
        jPanel1.add(jLabel1);

        rowsLabel.setText("0");
        jPanel1.add(rowsLabel);

        jLabel3.setText("Columns:");
        jLabel3.setEnabled(false);
        jPanel1.add(jLabel3);

        columnsLabel.setText("0");
        jPanel1.add(columnsLabel);

        jLabel5.setText("Charset:");
        jLabel5.setEnabled(false);
        jPanel1.add(jLabel5);

        charsetLabel.setText("utf8");
        jPanel1.add(charsetLabel);

        jLabel7.setText("Separator:");
        jLabel7.setEnabled(false);
        jPanel1.add(jLabel7);

        separatorLabel.setText("COMMA");
        jPanel1.add(separatorLabel);

        jLabel9.setText("Size:");
        jLabel9.setEnabled(false);
        jPanel1.add(jLabel9);

        sizeLabel.setText("0 Kb");
        jPanel1.add(sizeLabel);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel charsetLabel;
    public javax.swing.JLabel columnsLabel;
    private javax.swing.JTable columnsTable;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTable resultsTable;
    public javax.swing.JLabel rowsLabel;
    public javax.swing.JLabel separatorLabel;
    public javax.swing.JLabel sizeLabel;
    private javax.swing.JTable uniqueTable;
    // End of variables declaration//GEN-END:variables
}
